### ISSUE TITLE
Maintenance job behavior questions

### ISSUE THREAD

**Issue by DisgruntledHogi** [jobbish-sql/SQL-Server-Multi-Thread#1]
A few questions on the behavior of this maintenance solution - 

1.	Your readme calls out that the job is only supported for SQL 2016 SP2+ and 2017+, does that include 2019? 
2.	Some logging tables contain "one row per run of the maintenance solution" and "one row per attempted maintenance action" – do those ever get cleaned up, or will we need to implement our own solution for that? Or will they never get very large?
3.	What happens if the job gets killed by another process? . Will it overwrite the jobs on the next run? Will it error out because it's trying to create jobs that already exist?

**Comment by jobbish-sql** [comment]
Welcome to GitHub and thank you for reaching out! Here are answers to your questions:

1. The maintenance solution supports SQL Server 2019. I have updated the readme to be more clear on that point. Code reference here: https://github.com/jobbish-sql/SQL-Server-Multi-Thread/blob/master/core/sp_AgentJobMultiThread.sql#L453
2. The cleanup job deletes any data older than 100 days from the logging tables. Code reference here: https://github.com/jobbish-sql/SQL-Server-Multi-Thread/blob/master/cci_maintenance/CCI_Reorg_Rebuild_Code.sql#L2287
3. As possible, I recommend using the @max_minutes_to_run parameter and scheduling the job to start such that no jobs are killed by any other process. All work should automatically terminate before the time limit. If a job is killed by another process, the outcome depends on which job is killed.

The parent job typically runs for less than a minute. If it is killed then the impact can range from no jobs getting created or partial jobs getting created. Any child jobs created by the parent are likely to run as usual.

If the child jobs are killed then that's not a big deal. They are designed to be terminated by another process because the cleanup job calls sp_stop_job as needed.

The cleanup job runs once a minute until the workload is done and typically completes in just a few seconds. If the cleanup job is killed then it won't rerun. That is by design because I didn't want some unexpected error to cause the job to run for once a minute for eternity. So you could end up in a state where not all child jobs are terminated properly. However, if you have a process that's killing jobs then I assume that same process would also take care of the child jobs.


I am happy to answer any further questions.
